name: Create Artifact

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Compress Source Code and Info File
        run: |
          mkdir op
          cp -r src/ op/src
          cp info.toml op/
          cd op && zip -r MXRandom.op src/ info.toml

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MXRandom
          path: op/MXRandom.op
          
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: MXRandom
          path: op/MXRandom.op
