name: Create and Move Artifact

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Clean up old artifacts
        run: rm -rf op

      - name: Compress Source Code and Info File
        run: |
          mkdir op
          cp -r src/ op/src
          cp info.toml op/
          cd op && zip -r MXRandom.op src/ info.toml

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MXRandom
          path: op/MXRandom.op

      - name: Move Artifact to Main Files Directory
        run: cp op/MXRandom.op .

      - name: Display Main Files Directory
        run: ls

      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=release_id::$(curl -s -H \"Authorization: Bearer ${{ secrets.SECRET }}\" https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.0 | jq -r '.id')"

      - name: Upload Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release_id.outputs.release_id }}/assets?name=MXRandom.op
          asset_path: ./MXRandom.op
          asset_name: MXRandom.op
          asset_content_type: application/zip
