name: Create Release and Attach .op File
on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Compress Source Code and Info File
      run: |
        mkdir op
        cp -r src/ op/src
        cp info.toml op/
        cd op && zip -r MXRandom.op src/ info.toml
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload .op File
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: op/MXRandom.op
        asset_name: MXRandom.op
        asset_content_type: application/octet-stream
        release_id: ${{ github.event.release.id }}
